# Attaches a volume to a compute host
- name: attach volume to host
  os_server_volume:
    state: present
    server: '{{ instance_name }}'
    volume: '{{ volume_name }}'
    device: /dev/vdb
    timeout: 600


